### ISSUE TITLE
I'm curious what you're using NATS and deno for

### ISSUE THREAD

**Issue by samheutmaker** [nats-io/nats.deno#104]
Hey Brian! I hope you're doing well. I've been using NATS for a few different projects and just found Deno recently. I imagine that when you fork a project you dive deep, reengineer a bunch of stuff, and make it way better so I'm super curious what you're up to. Drop me a line if you're interested in chatting!

**Comment by aricart** [comment]
@samheutmaker not following the issue/thread here

**Comment by samheutmaker** [comment]
@aricart My apologies, this issue was meant for a fork of nats.deno that a friend made. Closing
