### ISSUE TITLE
Basic usage issue - can't import

### ISSUE THREAD

**Issue by edward653** [nats-io/nats.deno#109]
Just porting over my existing app from using amqp and rabbit mq to using nats.

I'll admit I have health dose of cluelessness - java developer hacking about in typescript - but I have a very basic problem. When I run my super simple app, this:

`
import { connect } from "https://deno.land/x/nats@v1.0.0-rc3/mod.ts";
`

Gives me this when I run:

`
Download https://deno.land/x/nats-base-client/mod.ts
Download https://deno.land/x/nats-base-client/transport.ts
Download https://deno.land/x/nats-base-client/internal_mod.ts
Download https://deno.land/x/nats-base-client/types.ts
error: Import 'https://deno.land/x/nats-base-client/mod.ts' failed: 404 Not Found
    at https://deno.land/x/nats@v1.0.0-rc3/mod.ts:2:0
`

I've tried on rc2 and rc1 also, in case there was a recent break.

I assume I'm doing something daft, but I can't for the life of me see what.

**Comment by edward653** [comment]
Confirmed everything works fine if I reference githubusercontent to get the development stream - but I'd prefer to work from demo.land hosted libraries. Seems like all the nats-base-client elements are trying to be picked up using an absolute path, rather than inside the nats@v1.0.0-rc3 folder where it is?

**Comment by aricart** [comment]
@edward653 this was on my radar for addressing. The deno.land/x website changed in august to be fully automatic. The optional directory option rooted the repo making it impossible for the module to access some of its dependencies. I have filed an issue https://github.com/denoland/deno_website2/issues/1671. That should un-wedge all the releases.

**Comment by aricart** [comment]
@edward653 this is fixed for deno.land/x/nats@v1.0.0-rc4

**Comment by edward653** [comment]
Brilliant - thank you sir.
