### ISSUE TITLE
Lister should be an AsyncIterator

### ISSUE THREAD

**Issue by nleguen** [nats-io/nats.deno#128]
jsm.streams.list() or jsm.consumers.list(stream) returns a Lister. Any reason why it cannot be used as an AsyncIterator ?

**Comment by aricart** [comment]
List is a paged result, `next()` is returning a list for the page. Not sure how that is helpful outside of the context of retrieving ALL streams and ALL consumers. But willing to consider it.

**Comment by nleguen** [comment]
#129
