### ISSUE TITLE
Header Changes

### ISSUE THREAD

**Issue by aricart** [nats-io/nats.deno#147]
# NATS HTTP Headers Redux

A long while ago, we discussed and agreed on the format of [NATS headers](https://github.com/nats-io/nats-server/blob/master/doc/adr/0004-nats-headers.md).

The specified format on the ADR linked above, has a couple of nuances:

- HTTP headers are supposed to be case insensitive
- The use of Go MIME headers, means that using non-raw map API, keys are serialized in canonical form.
- HTTP hack of having unmodified key values, not obvious, and doesn't provide any of the header API functionality that is expected.

```
const h = headers();
h.set("a-b", "xxxx");
h.append("A-B", "yyyy");
h.append("A-b", "zzzz");
```

This meant that serialized NATS headers render:

```
NATS/1.0
A-B: xxxx\r\n
A-B: yyyyy\r\n
A-B: zzzz\r\n
```

Keys are treated as case insensitive by the header API, because, the keys were always mapped to their canonical format, as per the specification. If a client doesn't comply, now that client is broken - ie lookups are done under Canonical Keys.

To preserve keys to be formatted as per the user, the serialization must allow:

```
NATS/1.0
a-b: xxxx\r\n
A-B: yyyyy\r\n
A-b: zzzz\r\n
```

While on the wire that is the format, the API would still honor case insensitivity on read:

```
h.values("a-B"); // ["xxxx", "yyyy", "zzzz"];
h.get("a-b"); // "xxxx"  - the first entry, whatever that means
```
The only problem then becomes manipulation of the entries.
One possible use of headers is to log processes that worked on the response. This is the reason why HTTP headers can have multiple values:

A->B->C->B->A

```
[B] h.set("Transform", "B");
[C] h.set("transform", "C"); <---- diff guy
```

If we use a map in the raw, this means that while multiple permutations are possible, values set with the same key, will NOT replace a value but instead aggregate:

```
[X] h.set("Transform", "X");
[Y] h.set("Transform", "Y");
```

The internal map representation must support:

```
Transform->["B", "C", "Y"];
transform->"C"
```

On rendering:

```
NATS/1.0
Transform: B\r\n
transform: C\r\n <--- note the header retains user specified key
Transform: X\r\n
Transform: Y\r\n
```

The only issue here is that if aggregation happens, all clients must implement header writing in the same way, or the least compliant will clobber:

- On set, if the key exists, it gets turned into a list (if not so already), and the new value is added - replacing values require a delete/add.
- Any user permutation on the key is allowed, collisions are handled by the rule above.

**Comment by scottf** [comment]
Currently the Java and .Net clients do not touch, do not normalize / canonicalize the keys, meaning they are case sensitive and `a-b` is a different key than `A-b`. The client is required to handle it's own case sensitivity. We write what we are given. Customer Tim requested that we at least provide an option. 

I don't think it's unreasonable to not provide an option for the user to enforce their own standard, but I can also see the case where we just simplify it for the user.

If we do not wish to provide options, I would the suggest 1 of these specifications in this, my order of preference:
1. Canonicalize the headers so `a-b`, `A-b`, `a-B` and `A-B` are all written `A-B` and can be looked with any of the 4 combinations, essentially case insensitive.
2. Do not touch user headers but look them up case insensitive.
3. Do not touch user headers and look them up case sensitive (this is what Java/.Net do right now)

Alternatively if we wish to provide options we could offer all 3 of these
1. Do not touch, lookup case-sensitive
2. Do not touch, lookup case-insensitive
3. Canonicalize, lookup case-insensitive

I agree that we need to quickly come to a consensus so if necessary. the clients can be changed before there is too much use.

**Comment by aricart** [comment]
nats.deno is going to implement it as described, keys will be written as per the user, get will return the first value in the first key that matches in a case insensitive way, likewise keys will return the union of all keys that match case-insentively.  No key normalization, headers are insensitive, if the user wants to store a canonical header, they can use the provide function to transform the key.

**Comment by wallyqs** [comment]
Same in Go if users decide to store/get in canonical header format they would use Set/Get which has that side effect of being stored in 'canonical format', but if those APIs are not used then headers are preserved as is, and since it is a map then can also do case-sensitive lookup, for example the following would be left as is:

```go
m.Header = http.Header{
		"CorrelationID": []string{"123"},
		"Msg-ID":        []string{"456"},
		"X-NATS-Keys":   []string{"A", "B", "C"},
		"X-Test-Keys":   []string{"D", "E", "F"},
	}
```

In general, we should take the option with the least surprise, so do not touch the keys and leave the keys as they are if possible.

**Comment by ColinSullivan1** [comment]
Would have to go char by char, detect a `"`, and allow those chars within a quoted string.  What is a string with an odd number of quotes?  Invalid header value?

w/r/t java, up to you...  .NET includes the get for the [] operator.

**Comment by scottf** [comment]
Regarding the quote, I have more information. https://tools.ietf.org/html/rfc7230#page-22

> The backslash octet ("\") can be used as a single-octet quoting
   mechanism within quoted-string and comment constructs.  Recipients
   that process the value of a quoted-string MUST handle a quoted-pair
   as if it were replaced by the octet following the backslash.

So if there is a quote in the data, it needs to be in double quotes AND backslashed

```
foo: "why would someone \" quotes",nothingspecial
```

As far as errors, if I can't parse it simply under these rules I have no idea yet what to do here

```
foo: "one quote " is technically legal , comma just for nightmares",nothingspecial
```

```

**Comment by ripienaar** [comment]
Whatever the outcome here, please update the ADR at the end so it reflects reality.

**Comment by watfordgnf** [comment]
Something that may not be simple for implementations is the following ordering PLUS case preservation constraint:
> ```
> [B] h.set("Transform", "B");
> [C] h.set("transform", "C"); <---- diff guy
> [X] h.set("Transform", "X");
> [Y] h.set("Transform", "Y");
> ```
> The internal map representation must support:
> ```
> Transform->["B", "C", "Y"];
> transform->"C"
> ```
> On rendering:
> ```
> NATS/1.0
> Transform: B\r\n
> transform: C\r\n <--- note the header retains user specified key
> Transform: X\r\n
> Transform: Y\r\n
> ```

Am I to understand that is the normative behavior expected by the clients?

If so a simple map type is not expressive enough.

**Comment by aricart** [comment]
> Currently the Java and .Net clients do not touch, do not normalize / canonicalize the keys, meaning they are case sensitive and `a-b` is a different key than `A-b`. 

The point of the spec is that they are NOT case sensitive. If the API clients on Java look for "a-B" using the _header_ api, you must return  the first value that matches case insensitively. If they request the values, you must return all of them. If there's a way of iterating over the key value pairs, you can have them in their code select the value they are looking for.

> The client is required to handle it's own case sensitivity. We write what we are given. Customer Tim requested that we at least provide an option.
> 
> I don't think it's unreasonable to not provide an option for the user to enforce their own standard, but I can also see the case where we just simplify it for the user.
> 
> If we do not wish to provide options, I would the suggest 1 of these specifications in this, my order of preference:
> 
> 1. Canonicalize the headers so `a-b`, `A-b`, `a-B` and `A-B` are all written `A-B` and can be looked with any of the 4 combinations, essentially case insensitive.

This is exactly what we are going away from. This is exactly the thing that motivated the change on the nats.deno. If we are supporting that keys remain as set, a library that assumes the keys are canonical, will not find equivalent but different case values.

> 2. Do not touch user headers but look them up case insensitive.
> 3. Do not touch user headers and look them up case sensitive (this is what Java/.Net do right now)

This has to be fixed. This means that some values set are invisible to Java.

> 
> Alternatively if we wish to provide options we could offer all 3 of these
> 
> 1. Do not touch, lookup case-sensitive
> 2. Do not touch, lookup case-insensitive
> 3. Canonicalize, lookup case-insensitive
> 
> I agree that we need to quickly come to a consensus so if necessary. the clients can be changed before there is too much use.

**Comment by aricart** [comment]
> Something that may not be simple for implementations is the following ordering PLUS case preservation constraint...

Ordering is not guaranteed.

**Comment by watfordgnf** [comment]
> > Something that may not be simple for implementations is the following ordering PLUS case preservation constraint...
> 
> Ordering is not guaranteed, unless we make it so - I for one vote we don't get into that.

The ADR seems to suggest NATS headers _are_ HTTP headers w.r.t. parsing, which would mean ordering is important within a header. The example given seems to suggest that as well.

> The desired outcome will be the NATS HEADER STANDARD, we can feel free to normalize this standard into something that makes sense from the API perspective and serializes into something that looks like HTTP headers.

I would very much enjoy a spelled out standard, especially given all of the differences brought up here.

**Comment by ripienaar** [comment]
At this point we have to assme the ADR is of no value and needs a rewrite, the ADR was a vague wishlist and written before the implementation - but implementation is not what the ADR says and was done (probably) without even reading the ADR.

I don't think we can realistically change the server at this point right? So whatever clients do that has to be carefully documented in the ADR as Client guidelines after updating the sections on what the server actually implement.

**Comment by aricart** [comment]
@ripienaar is spelling it out correctly, we didn't follow what we agreed on.

**Comment by wallyqs** [comment]
The server is ok since treating the headers opaquely (with the exception of JetStream headers which are [case-sensitive right now](https://github.com/nats-io/nats-server/pull/2094) but could be fixed to be case-insensitive as per the ADR and in an optimized way I think.  The part were we could expand in the ADR is about the API to fetch the values like Set, Get.  The Go client supports both case-sensitive (via the map) and case-insensitive lookups, but across languages what would work best I think is if `Set` preserves the key as is (does not change the data), and then make `Get` based lookup case-insensitive.

**Comment by aricart** [comment]
@scottf @wallyqs @ColinSullivan1 @watfordgnf 

I wrote some additional tests to confirm the go serialization for the headers that you can run for yourself if so inclined.
The outcome of this is the following functionality:

- Go will always perform key sensitive lookups, if accessing the map directly you can find values that are not canonical. Otherwise, only canonical keys are found.
- Get returns the first value
- Set replaces canonical key
- Comma-separated lists are not supported

For the other clients, this has significant meaning, which we can use to guide a spec. This also means that Go at some point may need to provide a wrapper to provide a consistent API that works across clients:

The proposed API is this:

- __GET__ - Returns the first value found by doing a case-insensitive lookup 
- __SET__ - Removes all case-insensitive matching keys and replaces them with the specified value. The key is written as provided
- __VALUES__ - returns a list of all values stored under the key (case insensitive) - API should return an empty list if not found. 
- __DELETE__ - deletes all matching keys (case insensitive) 
- For each value matching a key, a corresponding header is generated (no compacted comma-separated values should be emitted).
- All field names must be composed of printable ASCII characters (33-126), except for the COLON as this value separated the field from its value.
- All field bodies can have any ASCII characters except for `\r` or `\n`. As these are used to terminate the header line.


```go
package headers

import (
	"bytes"
	"fmt"
	"net/http"
	"strings"
	"testing"
)

func stringify(h http.Header) string {
	buf := new(bytes.Buffer)
	if err := h.Write(buf); err != nil {
		panic(err)
	}
	return buf.String()
}

func render(s string) string {
	s = strings.ReplaceAll(s, "\r", "␍")
	s = strings.ReplaceAll(s, "\n", "␊\n")
	return s
}

func Lines(t *testing.T, h http.Header) []string {
	buf := new(bytes.Buffer)
	if err := h.Write(buf); err != nil {
		t.Fatal(err)
	}
	s := buf.String()
	return strings.Split(s, "\r\n")
}

func TestGet(t *testing.T) {
    h := make(http.Header)
    h.Add("Two", "three")
    h.Add("Two", "four")
    h["two"] = []string{"five"}

    if len(h) != 2 {
        t.Fatal("unexpected number of keys")
    }
    if h.Get("Two") != "three" {
        t.Fatal("expected first key to be three")
    }
    if h.Get("two") != "three" {
        t.Fatal("expected two to be three")
    }
}

func TestSet(t *testing.T) {
    h := make(http.Header)
    h.Add("Two", "three")
    h.Add("Two", "four")
    if len(h) != 1 {
        t.Fatal("unexpected one key")
    }
    a := h.Values("two")
    if a[0] != "three" && a[1] != "four" {
        t.Fatal("unexpected values found")
    }
    h.Set("two", "B")
    if len(h) != 1 {
        t.Fatal("expected one key")
    }
    a = h.Values("two")
    if len(a) != 1 {
        t.Fatal("expected only one value")
    }
    if a[0] != "B" {
        t.Fatal("unexpected value")
    }
}

func TestValues(t *testing.T) {
    h := make(http.Header)
    h.Add("Two", "three")
    h.Add("Two", "four")
    h["two"] = []string{"five"}

    if len(h) != 2 {
        t.Fatal("unexpected number of keys")
    }
    if len(h.Values("Two")) != 2 {
        t.Fatal("Two to have two values")
    }
}

func TestDelete(t *testing.T) {
	h := make(http.Header)
	h.Add("Two", "three")
	h.Add("Two", "four")
	h["two"] = []string{"five"}

    if len(h) != 2 {
        t.Fatal("unexpected number of keys")
    }
    h.Del("Two")
    if len(h) != 1 {
        t.Fatal("unexpected number of keys")
    }
    if h.Get("two") != "" {
        t.Fatal("expected two not to be found")
    }
    if len(h["two"]) != 1 {
        t.Fatal("expected two be found with direct map access")
    }
}

func TestCommaSeparatedList(t *testing.T) {
	h := make(http.Header)
	h["One"] = []string{"one,two"}
	h.Add("Two", "three")
	h.Add("Two", "four")

	a := h.Values("One")
	if len(a) != 1 {
		t.Fatal("go renders comma as different values")
	}
}

// Go renders multiple entries as a single key
func TestDirectEntriesRenderAsMultipleKeys(t *testing.T) {
	h := make(http.Header)
	h["hello"] = []string{"world", "mars"}
	lines := Lines(t, h)

	if len(lines) != 3 {
		t.Fatal(fmt.Sprintf("should have had 3 (%d) lines: %v", len(lines), lines))
	}
	for _, l := range lines {
		if l == "" {
			continue
		}
		if !strings.HasPrefix(l, "hello") {
			t.Fatal(fmt.Sprintf("unexpected prefix: %s", l))
		}
	}
}

// Go renders multiple entries as a single key
func TestEntriesRenderAsMultipleKeys(t *testing.T) {
	h := make(http.Header)
	h.Add("hello", "world")
	h.Add("Hello", "mars")

	lines := Lines(t, h)

	if len(lines) != 3 {
		t.Fatal(fmt.Sprintf("should have had 3 (%d) lines: %v", len(lines), lines))
	}
	for _, l := range lines {
		if l == "" {
			continue
		}
		if !strings.HasPrefix(l, "Hello") {
			t.Fatal(fmt.Sprintf("unexpected prefix: %s", l))
		}
	}
}

func main() {
	h := make(http.Header)
	h.Add("hello", "world")
	h.Add("Hello", "mars")
	h.Add("HELLO", "saturn, jupiter")
	h["hellO"] = []string{"venus"}

	v := h.Values("hello")
	fmt.Printf("`hello` key: %v\n", v)

	fmt.Println(render(stringify(h)))
}
```

**Comment by wallyqs** [comment]
Also to note, that in the Go client the implementation of the http header is also just an alias to a type:

```go
type Header map[string][]string
```

so opting in/out of using canonical Set/Get does by default is trivial since can just do a cast and use a different implementation, e.g.

```
type myHeader map[string][]string

func (h myHeader) Set(key, value string) {
	myHeader[key] = []string{value}
}

func (h myHeader) Get(key string) string {
	return myHeader[key][0]
}

func main() {
	h := make(myHeader)
	h.Set("hello", "world")
	mh := http.Header(h) // back to http 
}
```

What seems that would work better for us is for these helpers in other languages to be case-insensitive on get/values as mentioned to avoid reimplementing the 'canonical format' from the Go libraries, and not changing the keys on Set to avoid incompatibility issues like it happens with some Go based http proxies.

**Comment by aricart** [comment]
Yes, this is correct. However, the issue will be that the type does offer the API and unless folks understand some of the operations will not yield the right values. That is if you set the key `foo` that key won't be found unless the code is written to access the map. With that said, we can have another library wrap the header to perform the manipulations in away that it is transitive to the other libraries.

**Comment by aricart** [comment]
Also - if the lib is case-insensitive, ALL operations must behave so, otherwise, we'll have a mix of behaviours.

**Comment by aricart** [comment]
The final implementation is:

- [change - breaking] By default, NATS headers are now case sensitive by default, a `Match`. This means that headers are set/retrieved with an exact match of the specified key. Previously keys were transformed to a Canonical MIME format, and then serialized. To have compatibility with this previous behaviour, specify `Match.CanonicalMIME` (number value of `1`) as an argument to the header API.
- [feat] A new `Match` argument provides 3 different strategies:
    - `Exact` (`0`) - the __default__, all headers are set/read matching the exact provided key.
    - `CanonicalMIME` (`1`), headers are transformed to their Canonical representation, and an exact match is performed.
    - `IgnoreCase` (`2`), the API is case-insensitive
       - `get` will return the first value found from the union of all equivalent headers
       - `values` will return the union of all values stored under equivalent headers
       - `has` will return `true` if any equivalent header exists
       - `append` will add a value to the first header matched. If not matched a new header is set preserving the header name as specified by the user.
       - `delete` will remove _all_ equivalent header entries
       - `set` will perform a `delete` followed by an `append`.
- [change - breaking] `Status` and `Description` header entries are removed. These values are accessible from `status`, `code`, and `description` properties in the header object.
- [change] the function `canonicalMIMEHeaderKey` can be accessed by client code to transform the specified header key into its canonical MIME representation.
