### ISSUE TITLE
Subscription callbacks aren't called on connection reconnect

### ISSUE THREAD

**Issue by connorclockwise** [nats-io/nats.deno#180]
When a subscription is made on a remote nats server, the subscription callback is never called again if the connection is reconnected. 

Steps to reproduce:

1. Setup a nats server on a remote host (a vm, docker image, what have you)
2. Publish messages on the remote host on some interval
3. Connect to the remote nats server using the nats.deno javascript client
4. Create a subscription on the remote nats connection with a callback
5. Disconnect the remote host from the internet (disable the ethernet adapter for a vm or the equivalent on a docker image)
6. Reconnect the remote host to the internet

Expected Results:
The callback is called during the initial connection and after the reconnection 

Actual Results:
The callback is called during the initial connection and after that it is never called again 

Notes:
Neither the connection nor the subscription is marked as closed. Connection status is observed as  "reconnected" to the remote host ip. During debugging, incoming messages were seen [hitting this line](https://github.com/nats-io/nats.deno/blob/36b969c8dd7658b5af06131341c25329df3bf5aa/nats-base-client/protocol.ts#L482) on initial connection and then never again after reconnect.

Code to reproduce below. Assumes:

Tested on node v12.16.1
Nats npm package version 2.1.0 
Remote host is a windows 7 vm running nats server version 2.2.2
Stream already setup on nats server with subject filter `*.general`

Example publisher code to reproduce, run on remote host:
```node

async function start(){
  const { connect, StringCodec } = require("nats");
  const sc = StringCodec();
  
    const configuration = {
        servers: "nats://localhost:4222",
        debug:true
    };
    
    const connection = await connect(configuration);
    
     setInterval(() => {
        const message = sc.encode("My message on  an interval.");
        connection.jetstream().publish("example.general",   message);
     }, 1000);
}
start();
```

Example subscription code to reproduce,  run on client host:
```node

async function start(){
  const { connect, StringCodec, consumerOpts, createInbox } = require("nats");
  const sc = StringCodec();
  
    const configuration = {
        servers: "nats://<The_Ip_Of_The_Remote_Host>:4222",
        debug:true
    };

    const callback = (error, message) => {
      if (error) {
        console.error(error);
      } else {
        const sequence = message.seq;
        let data = "";
        if (message && message.data) {
          data = sc.decode(message.data);
        }
        console.log(`Received a message [${sequence}] ${data}`);
        message.ack();
      }
    };

    const subscriptionOptions = consumerOpts();
    subscriptionOptions.ackExplicit();
    subscriptionOptions.deliverTo(createInbox());
    subscriptionOptions.callback(callback);
    
    const connection = await connect(configuration);
    const subscription = await connection.jetstream().subscribe("example.general", subscriptionOptions);
}
start();
```

**Comment by talhof8** [comment]
Experiencing the same issue. Does it also happen for non-JetStream subscriptions for you?

**Comment by aricart** [comment]
Thanks for the report. Will take a look

**Comment by aricart** [comment]
@connorclockwise how long is the disconnect happening for, your consumer doesn't have a durable associated it with so it is ephemeral, meaning that soon after it disconnects it is gone!

**Comment by connorclockwise** [comment]
Hey @aricart,  thanks for the quick response time. I tried the updating the consumer options builder to include a durable subscription name and I saw the same issue.
```
const subscriptionOptions = consumerOpts();
  subscriptionOptions.ackExplicit();
  subscriptionOptions.deliverTo(createInbox());
  subscriptionOptions.callback(callback);
  subscriptionOptions.durable("durableName");
```

**Comment by aricart** [comment]
@connorclockwise can you verify that the server is storing in a stream that is file-based?
I did a test, and I see the deliver-to subscription be re-created and receive not only the messages that were pending but some new ones I send after re-starting the server.

**Comment by aricart** [comment]
```
test jetstream - durable resumes ...nats 50374
 >> jetstream functionality in nats.deno is preview functionality 
# this is the deliver_to subject:
deliver subject _INBOX.U4A4P8LED6OX7LV69TAJK3
# received 3 messages from the stream:
a
b
c
# Restart the server
stopped
< 
> INFO {"server_id":"NCKZPOZAJ6S2XHWLVVTOOMHZB36PGYY6EV2FUBWHPG5AYUEN4TP76JZ7","server_name":"NCKZPOZAJ6S2XHWLVVTOOMHZB36PGYY6EV2FUBWHPG5AYUEN4TP76JZ7","version":"2.3.5-beta","proto":1,"go":"go1.16.4","host":"127.0.0.1","port":50374,"headers":true,"max_payload":1048576,"jetstream":true,"client_id":9,"client_ip":"127.0.0.1"} ␍␊
< CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"lang":"nats.deno","version":"1.0.6","headers":true}␍␊
< PING␍␊
> PONG␍␊
# Note sub to SUB _INBOX.U4A4P8LED6OX7LV69TAJK3 is the deliver_to
< SUB _INBOX.U4A4P8LED6OX7LV69TAIKX.* 1␍␊SUB _INBOX.U4A4P8LED6OX7LV69TAJK3 2␍␊
restarted
< PING␍␊
> PONG␍␊
# published some new messages `d`, `e`, `f`
< HPUB U4A4P8LED6OX7LV69TAI97.A _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAK7J 0 3␍␊"d"␍␊
> MSG _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAK7J 1  44␍␊{"stream":"U4A4P8LED6OX7LV69TAI97", "seq":4}␍␊MSG U4A4P8LED6OX7LV69TAI97.A 2 $JS.ACK.U4A4P8LED6OX7LV69TAI97.me.1.4.4.1628872098454569000.0 3␍␊"d"␍␊
d
< HPUB U4A4P8LED6OX7LV69TAI97.A _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKDE 0 3␍␊"e"␍␊PUB $JS.ACK.U4A4P8LED6OX7LV69TAI97.me.1.4.4.1628872098454569000.0 4␍␊+ACK␍␊
> MSG _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKDE 1  44␍␊{"stream":"U4A4P8LED6OX7LV69TAI97", "seq":5}␍␊MSG U4A4P8LED6OX7LV69TAI97.A 2 $JS.ACK.U4A4P8LED6OX7LV69TAI97.me.1.5.5.1628872098460713000.0 3␍␊"e"␍␊
e
< HPUB U4A4P8LED6OX7LV69TAI97.A _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKJ9 0 3␍␊"f"␍␊PUB $JS.ACK.U4A4P8LED6OX7LV69TAI97.me.1.5.5.1628872098460713000.0 4␍␊+ACK␍␊
> MSG _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKJ9 1  44␍␊{"stream":"U4A4P8LED6OX7LV69TAI97", "seq":6}␍␊MSG U4A4P8LED6OX7LV69TAI97.A 2 $JS.ACK.U4A4P8LED6OX7LV69TAI97.me.1.6.6.1628872098467018000.0 3␍␊"f"␍␊
f
< PING␍␊PUB $JS.ACK.U4A4P8LED6OX7LV69TAI97.me.1.6.6.1628872098467018000.0 4␍␊+ACK␍␊PING␍␊
> PONG␍␊PONG␍␊
< UNSUB 2␍␊PUB $JS.API.STREAM.INFO.U4A4P8LED6OX7LV69TAI97 _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKP4 0␍␊␍␊
> MSG _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKP4 1 548␍␊{"type":"io.nats.jetstream.api.v1.stream_info_response","config":{"name":"U4A4P8LED6OX7LV69TAI97","subjects":["U4A4P8LED6OX7LV69TAI97.A"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"duplicate_window":120000000000},"created":"2021-08-13T16:28:18.266189Z","state":{"messages":6,"bytes":342,"first_seq":1,"first_ts":"2021-08-13T16:28:18.281985Z","last_seq":6,"last_ts":"2021-08-13T16:28:18.467018Z","consumer_count":1}}␍␊
< PUB $JS.API.CONSUMER.INFO.U4A4P8LED6OX7LV69TAI97.me _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKUZ 0␍␊␍␊

# For the state of the consumer:
# "delivered":{"consumer_seq":6,"stream_seq":6} - all messages delivered and ack'ed

> MSG _INBOX.U4A4P8LED6OX7LV69TAIKX.U4A4P8LED6OX7LV69TAKUZ 1 655␍␊{"type":"io.nats.jetstream.api.v1.consumer_info_response","stream_name":"U4A4P8LED6OX7LV69TAI97","name":"me","created":"2021-08-13T16:28:18.321954Z","config":{"durable_name":"me","deliver_subject":"_INBOX.U4A4P8LED6OX7LV69TAJK3","deliver_policy":"all","ack_policy":"explicit","ack_wait":30000000000,"max_deliver":-1,"filter_subject":"U4A4P8LED6OX7LV69TAI97.A","replay_policy":"instant","max_ack_pending":20000},"delivered":{"consumer_seq":6,"stream_seq":6},"ack_floor":{"consumer_seq":0,"stream_seq":0},"num_ack_pending":3,"num_redelivered":0,"num_waiting":0,"num_pending":0,"cluster":{"leader":"NCKZPOZAJ6S2XHWLVVTOOMHZB36PGYY6EV2FUBWHPG5AYUEN4TP76JZ7"}}␍␊
< 
```

**Comment by aricart** [comment]
You can activate a protocol trace on the client by providing the `debug: true` connection option.

**Comment by aricart** [comment]
@connorclockwise also can you verify the server version you are using? Unfortunately on my case I am using one that I built from master today, so it is possible that some other version is not behaving correctly.

**Comment by connorclockwise** [comment]
@aricart Hey, I am using the file based message store and I had the debugging option already toggled on. I do not see any messages coming through after the disconnect. 

I am currently using the nats-server 2.2.2. I can upgrade the server if you think that will yield different results. I didn't see any changes/fixes for this issue in any of the nats server changelogs. Interestingly enough the nats cli go client does not share this issue with the javascript client; I am able to subscribe, disconnect the host server, reconnect, and watch new messages arrive on the nats cli.

For posterity: The issue is not visible if you shut down the server yourself. It is only visible if you manually disable the host machine's ethernet adapter or otherwise disconnect the server host's network connection.

**Comment by aricart** [comment]
Can you attach the log?

**Comment by aricart** [comment]
And yes server version could have something to do.  Are you in a cluster environment?

**Comment by connorclockwise** [comment]
Hey @aricart I just checked the logs and I was seeing the messages I missed from earlier. The durable name suggestion you provided earlier worked just fine, I did not give it enough time to recreate the subscription. Thanks very much for walking me through this process!
