### ISSUE TITLE
Consider making jwtAuthenticator function async

### ISSUE THREAD

**Issue by manifest** [nats-io/nats.deno#236]
It'd make possible retrieving credentials over the network.

```javascript
const nc = await connect({
    ...
    authenticator: jwtAuthenticator(() => await fetch("https://example.org/tokens")),
});
```

Currently, above example [isn't possible](https://github.com/nats-io/nats.deno/blob/c70cc014f5c1ee37fdef0ccb98298835bd79b5d2/nats-base-client/authenticator.ts#L126).

**Comment by manifest** [comment]
In our apps, we're already using token-based authentication. It'd be nice to have a simple way of exchanging tokens.

**Comment by aricart** [comment]
Async doesn't work for the authentication - if the authentication doesn't resolve when needed the server will disconnect (rather quickly). So effectively if connect is called, the authentication data needs to already be available. This doesn't mean however that you could have some sort of background timer that updates the authentication data that we require, then it would be available when needed.
