### ISSUE TITLE
Error on nats import (StartTlsOptions)

### ISSUE THREAD

**Issue by mullerch** [nats-io/nats.deno#243]
When running a deno file with nats import, the following error occurs:

```
error: TS2345 [ERROR]: Argument of type '{ hostname: string; certFile: string | undefined; }' is not assignable to parameter of type 'StartTlsOptions'.
  Object literal may only specify known properties, and 'certFile' does not exist in type 'StartTlsOptions'.
      { hostname, certFile: tls.caFile },
                  ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/nats@v1.4.0/src/deno_transport.ts:146:19
```

## Reproduction

Create a main.ts file with the following content:

```
import * as nats from "https://deno.land/x/nats@v1.4.0/src/mod.ts";
```

Run with `deno run main.ts`

## Version
```
deno --version
deno 1.17.2 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

## Workaround

Use raw import:

```
import * as nats from "https://raw.githubusercontent.com/nats-io/nats.deno/main/src/mod.ts";
```

**Comment by aricart** [comment]
`StartTlsOptions` is a Deno type - The client doesn't export it.  The `TlsOptions`  is the one exported by the NATS library.
Not sure why you are getting that error, `certFile`, etc - are converted by the client to what is appropriate on the runtime:

https://github.com/nats-io/nats.deno/blob/main/src/deno_transport.ts#L133

**Comment by aricart** [comment]
If you upgraded Deno recently, they changed their tls configuration recently - you may want to 
`deno cache --unstable --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/src/mod.ts`

**Comment by mullerch** [comment]
I've just installed deno in that given version. The reload does no solve the issue.

I've installed deno with `curl -fsSL https://deno.land/install.sh | sh`. Running ubuntu 21.10.

**Comment by playerx** [comment]
I've the same issue.
```
deno 1.17.3 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

As I see from the error incorrect option is passed in `Deno.startTls`

New api looks like this:
```ts
  export interface StartTlsOptions {
    /** A literal IP address or host name that can be resolved to an IP address.
     * If not specified, defaults to `127.0.0.1`. */
    hostname?: string;
    /** A list of root certificates that will be used in addition to the
     * default root certificates to verify the peer's certificate.
     *
     * Must be in PEM format. */
    caCerts?: string[];
  }
```

and in `nats-deno` the following options are passed: `{ hostname, certFile: tls.caFile }`

**Comment by playerx** [comment]
@mullerch  as a workaround you can pass `--no-check` flag if you don't need to pass `caCerts` and it will ignore this typescript type mismatch issue and caCerts will be `undefined` always

**Comment by aricart** [comment]
See https://github.com/nats-io/nats.deno/pull/232

**Comment by aricart** [comment]
If you update to v1.5.0, you should no longer see this issue. Note that it also raises the lowest version of Deno to 1.16.x  - https://deno.land/x/nats@v1.5.0

**Comment by mullerch** [comment]
It fixes the issue, thanks!
