### ISSUE TITLE
JetStreamManager.update() requires stream name in cfg object?

### ISSUE THREAD

**Issue by JH7** [nats-io/nats.deno#256]
Calling the JetStreamManager.update() method like this (using the nats.js in node.js):
```js
jcm.streams.update('test', options);
```
throws the error:
```js
{"name":"NatsError","code":"500","api_error":{"code":500,"err_code":10052,"description":"stream name is required and can not contain '.', '*', '>'"}}
```

My guess is that the stream name has to be included in the `cfg` object used here:
https://github.com/nats-io/nats.deno/blob/d698a5ad688bba907fc2cdb962b360bc75ff6fd3/nats-base-client/jsmstream_api.ts#L78-L81

If I manually include the name like so `jcm.streams.update('test', { name: 'test', ...options});`, the error is not thrown.

Additionally, the TypeScript declaration of `StreamUpdateConfig` does not include `subjects`, even though I was able to call the `update()` method with a `cfg` object including `subjects` and the stream seemed to be updated correctly.
https://github.com/nats-io/nats.deno/blob/5bf5482cd2e62a12e8a4dfe350624794491a0254/nats-base-client/types.ts#L560-L572
Furthermore: Are `max_msgs`, `max_age` and `max_bytes` really mandatory for an update (as shown in the TS interface)?

I'm not into the server/protocol implementation of NATS, so I currently cannot check whether my assumptions are actually true or not, so apologies if I'm missing something.

**Comment by aricart** [comment]
The incorrect thing is: `update(name: string, cfg: StreamUpdateConfig): Promise<StreamInfo>` - this should be:
`update(name: string, cfg: Partial<StreamUpdateConfig>): Promise<StreamInfo>` which will relax all fields except for the ones you are changing. The library can inject the `name` for you as that is provided as a separate argument.

**Comment by JH7** [comment]
> @JH7 what server/client version are you on?

Server: 2.7.2
Client (nats): 2.6.0

**Comment by aricart** [comment]
fixed by https://github.com/nats-io/nats.deno/pull/258
