### ISSUE TITLE
Authentication failures sometimes result in `ConnectionRefused` exceptions instead

### ISSUE THREAD

**Issue by Kjir** [nats-io/nats.deno#268]
When the reconnect attempts are exhausted, a `ConnectionRefused` exception is thrown.

https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L342

However, this can occur even for expired authentication cases (it does in my application) and it's impossible to determine whether there is a problem connecting to the server (e.g.: it's down) or if some other thing happened. Probably a more specific error would help determine what caused the attempts to be exhausted.

**Comment by Kjir** [comment]
I just realized that it should throw the last error, but I instead get the generic "Connection Refused" error. I'm trying to determine why that is the case - I know for a fact that the error is an authentication error.

**Comment by Kjir** [comment]
What I figured so far: the code goes into this condition here
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L434

However in the `dialLoop()` the `lastError` is `undefined`:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L342

I'm trying to understand why this is happening

**Comment by Kjir** [comment]
Ok so I figured out more or less what are the conditions to end up there.

First of all I open a new connection that will run the dialLoop:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L376

Then my JWT token has expires and we stop the reconnect attempts:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L435
And we disconnect:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L440

Now since the transport got closed, but the connection is not closed, we trigger the disconnected handler:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L228

And here since we have specified in our options that we'd like to reconnect, it runs the dialLoop again:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L249
But it will refuse to try and connect since we disabled the reconnection attempts above!
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L341
We get a generic "Connection Refused" error because we did not have the original error with us.

So we now close the connection, and we return to the client the "Connection Refused" (wrongly) instead of the "Autentication Expired" error:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L690


I'm not sure about the purpose of all this logic, however I believe that there is either a mistake here, where we're supposed to check the value of  `this.abortReconnect` as well:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L248

Or it's a mistake here and we should just call `this._close(err)` instead:
https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L690

**Comment by Kjir** [comment]
I forgot to mention that this issue seems to be dependent on the server: I have a NATS server running on my machine and with that one, it works perfectly.
If I connect to the NATS server on the staging environment, however, the problem appears.

**Comment by aricart** [comment]
@Kjir what versions are you on?

**Comment by Kjir** [comment]
I am using `nats.ws` which is currently at version 1.6.0. I just saw that I should upgrade, I'll do that and check if it still applies.

The NATS server is the same in both environments and it is `2.6.5`

**Comment by Kjir** [comment]
I just upgraded and verified that is still happens in version `1.7.2` of `nats.ws`

**Comment by aricart** [comment]
are you by any chance behind a load balancer?

**Comment by Kjir** [comment]
Yes - NATS is running in a cluster. In case of staging, there are multiple nats servers running, but all reachable by the same domain name

**Comment by Kjir** [comment]
But that would not match my observations - no connect attempt is made that is being ignored. The websocket connection gets interrupted for the right reason (authentication expired), it's just that the javascript library raises the wrong error

-------- Original Message --------

**Comment by aricart** [comment]
what are your connect settings?

**Comment by aricart** [comment]
it may be that it retried the max number of times, and gave up - so effectively couldn't connect

**Comment by Kjir** [comment]
I open the connection with these options:
```
  const connection = await connect({
    servers: [Environment.natsUrl],
    pingInterval: 59000,
});
```
I tried adding `ignoreClusterUpdates: true` but it didn't change anything

The number of retries is 10 (default), but it doesn't do 10 retries. I traced the path it takes here: https://github.com/nats-io/nats.deno/issues/268#issuecomment-1055565715

**Comment by Kjir** [comment]
Here are some logs that I added to the `nats.ws` code to try and trace what is going on. I prefixed every log with the name of the function, they all come from the [ProtocolHandler class](https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L119)

Here are the logs for the successful case, where I get the correct error: https://paste.ofcode.org/36WUrs6xmd3yyeuzNCMLjug

These are the logs for the bad case, where I get the generic `Connection Refused` error: https://paste.ofcode.org/3GswAYK5gTgKnxfDFtLqe8

(I replaced the domain with `<domain>` manually)

The difference that strikes me the most is that in the failing case there is an `Events.Reconnect` that doesn't appear in the good case, which is probably a clue in the right direction

**Comment by Kjir** [comment]
I think I figured out what happens.
In the failure case, I see after the first connection get closed for authentication failure, the second one that is opened to attempt the reconnection receives a `PONG` right before receiving an `ERR 'User Authentication Expired'`.

![image](https://user-images.githubusercontent.com/64094/156464444-028b8726-f0a1-4bdd-8a6f-223431767840.png)

In the success case, no such `PONG` is received:
![image](https://user-images.githubusercontent.com/64094/156464592-aba7c0ce-3873-47b7-a197-ea98b4dc9956.png)

At the code level, when a `PONG` is received, the `dial` operation succeeds and removes the `connectError` function. It means that it thinks the connection was established successfully. However the next Authentication Error matches the Authentication Error from the previous connection, so it will stop the reconnects. But since the the dial loop was started anew when reconnecting, the `lastError` local variable is unset: https://github.com/nats-io/nats.deno/blob/afc6da4cea96acc4b5b8dfc225bf3289ad527db6/nats-base-client/protocol.ts#L334

I wonder if it should reference `this.lastError` instead?
Another possibility would be to reset `this.lastError` and `this.abortReconnect` when the `PONG` is received.

I honestly see downsides with both:

First approach: if you have a connection that stays open for a while and then expires, the authentication is refreshed, it tries to reconnect and it succeeds. After a while it expires again -> This is twice the same error in a row, it won't reconnect.

Second approach: In the scenario where the server sends a `PONG` before saying `Authentication Expired`, it would try to reconnect up to `maxReconnectAttempts` times, the mechanism of "Exit if you get the same authentication failure twice in a row" would not work anymore


Is it expected/normal that the server can send a `PONG` even though the JWT used for authentication is already expired? Why does one server send it and the other doesn't?

**Comment by Kjir** [comment]
As far as I understand it, this is what happens currently (assuming no `PONG` from the server), which is not correct, I believe:

```mermaid
gantt
    title NATS Websocket with JWT Auth
    dateFormat  mm:ss
    axisFormat %X
    section Websocket (NATS)
    First connection           :c1, 00:00, 10m
    NATS Server Authentication Expired : milestone, nats_auth_exp
    Second connection (Reconnect)     :after c1  , 10m
    NATS Server Authentication Expired : milestone, nats_auth_exp2
    Connection closed : milestone, nats_conn_closed
    section Other events
    Refresh JWT      :08:30  , 10s
    Refresh JWT      :18:30  , 10s

```

**Comment by aricart** [comment]
@Kjir I will take a look at this as soon as I can dig out from the current deadline I have.

**Comment by Kjir** [comment]
> I think the issue here is specific to nats.ws. For the nats.js and nats.deno transports the behavior is not like this.
What do you mean? I linked the logic above and all the logic resides in nats.deno. nats.ws is just a wrapper around that...

If I manage to find some time I'll try to write a test to show the behaviour described in https://github.com/nats-io/nats.deno/issues/268#issuecomment-1057520161

About the `PONG` received by the server, I don't know where it comes from. Maybe it's a bug with NATS server itself? It's a bit beyond my current understanding of the project, unfortunately...

...and good luck with your deadline :smile:

**Comment by Kjir** [comment]
Ah I understand now!

Well you know when you don't understand why something behaves a certain way and you *have* to find out why? This comes from that :sweat_smile:

**Comment by aricart** [comment]
@Kjir sorry for the delay on this one - now the client will present you with the proper error. Thanks for the awesome bug report.

**Comment by Kjir** [comment]
Thank you for the awesome fix :wink:
