### ISSUE TITLE
heartbeat timer leaks

### ISSUE THREAD

**Issue by john-livelyvideo** [nats-io/nats.deno#272]
we are seeing timer leaks originating here:
https://github.com/nats-io/nats.deno/blob/e99ff62cda261d3a98fefc4707c89fa8fdf74b32/nats-base-client/heartbeats.ts#L61-L61

is there anything wrong w/ calling clearTimeout here:
https://github.com/nats-io/nats.deno/blob/e99ff62cda261d3a98fefc4707c89fa8fdf74b32/nats-base-client/heartbeats.ts#L62-L62

also, is the 'undefined' check being done consistently?

**Comment by aricart** [comment]
what client?

**Comment by aricart** [comment]
Also - not following why the cleanup on dispatch - the only reason dispatch is getting called is that the timer fired. It is not an interval, but a timer, so once the timer fires (which does the dispatch), it is reaped, a new one will schedule, but again - it is not an interval, but a timer.

**Comment by john-livelyvideo** [comment]
"nats": "^2.6.1",

**Comment by john-livelyvideo** [comment]
i may have been wrong, looked like an async loop to me.

**Comment by aricart** [comment]
the timer schedules a ping to the server, and clears all pending pings on the first pong of that kind that is resolved, if more than the threshold are open, then the client closes, as it is partitioned from the server.

**Comment by john-livelyvideo** [comment]
got it.  in that case, socket descriptors are definitely cleaned up.  but, timer handles/descriptors are accumulating.

**Comment by aricart** [comment]
Only timers are - connectTimer - fails a connection if protocol connection doesn't happen on specified time, one for each request that you make, which either resolves or fails (and your code would be aware of it), subscription timeouts if you set them, for auto flushing if when you publish no other data is in the buffer, and finally to schedule hold the dial loop.

**Comment by aricart** [comment]
Also - for sanity, the nats.js doesn't do any timer on its own.

**Comment by john-livelyvideo** [comment]
I'm confused, there are no heartbeat timers in the client?

**Comment by john-livelyvideo** [comment]
Not sure I understand.  Meaning all timer code is in the deno codebase?

**Comment by aricart** [comment]
Correct. - All timers are started from the common library.

**Comment by john-livelyvideo** [comment]
reaped, are we saying timers get gc'd w/o calling cleartimeout?  to be honest, i don't know what to believe ... below clearTimeout looks like a necessity?

>The handler of the timeout will stay active and in memory even after the timeout happened. Because the handler stays active his dependencies cannot be collected either.

https://medium.com/@galbatz/memory-model-memory-leaks-in-node-js-395d63b8ba11

**Comment by john-livelyvideo** [comment]
are we making the argumen v8 timers are composed of v8 allocated memory?  and because of this, they cannot leak?  i realize a socket/descriptor leak also leaks on the kernel side.  but even if v8 memory is leaking due to some ref situation, lack of clearTimeout, etc. it's still a problem, right?

**Comment by aricart** [comment]
as per JavaScript - timers and intervals keep the event loop alive but don't leak memory - a timer is self-removed when it fires, intervals need to be canceled when not needed. So no, if you `setTimeout(()=>())`, it will fire in the next event loop and you don't need to do anything else - if you instead `setTimeout(()=>{}, 100000000)` you may want to clean that up if you don't need it at some point.

**Comment by john-livelyvideo** [comment]
@aricart got it, thx.  For my own edification, may I get the link to the above?

**Comment by aricart** [comment]
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-cleartimeout-dev

is the specification, you'll want 8.6, and see '9.6' which states that if not a repeating timer, then the timer is removed from the map of active timers.
