### ISSUE TITLE
ReadableStream web API and NodeJS < 18.x

### ISSUE THREAD

**Issue by jmordica** [nats-io/nats.deno#356]
In order to use the Object store methods, are we required to use the latest Node 18.x (which includes fetch etc..)?

It seems in the example you are using ReadableStreams (I assume because this is actually a Deno module).

Also, in `objectstore.js` you are calling:
```js
const reader = rs ? rs.getReader() : null;
```

Thanks for any input here 😄

**Comment by aricart** [comment]
it should not require fetch - the only limitation is you need a version of crypto that supports the webcripto. The W3C ReadableStream support/interfaces are supplied by `web-streams-polyfill` in node, as node has a different concept for readable streams. As a user of the interface, all you have to do is provide an object that supplies the required functions, and it just works - see https://github.com/nats-io/nats.deno/blob/main/jetstream.md#objectstore

The sanity test for object store on node only skips on node 14, as that version doesn't have the webcrypto support we require for the hash verification and generation. I test on 16 and 18 by default - CI tests on 14, 16, 17!  - I have to bump that to 18. 

Is there any particular issue you are experiencing? In other issues you are always running nats.ws on node, which perhaps it not providing a shim that is required in node, but not in nats.ws which is intended for W3C (browser) apis.

In that case you may try, adding a dependency on `web-streams-polyfill` and then shimming it up like:

```javascript
if (typeof globalThis.ReadableStream === "undefined") {
  const streams = require("web-streams-polyfill/ponyfill");
  global.ReadableStream = streams.ReadableStream;
}
```

The node.js version of the library does this: https://github.com/nats-io/nats.js/blob/main/src/mod.ts

**Comment by jmordica** [comment]
Sweet, this got me going. Thanks for the explanation as well!
