### ISSUE TITLE
New object store file upload example

### ISSUE THREAD

**Issue by jmordica** [nats-io/nats.deno#357]
When using NodeJS to upload a file via like:
```js
await os.put({name: 'filename.gz'}, this.readableStreamFrom(fs.readFileSync(./filename.gz)))
```

```js
readableStreamFrom(data: Uint8Array): ReadableStream<Uint8Array> {
  return new ReadableStream<Uint8Array>({
    pull(controller) {
      controller.enqueue(data);
      controller.close();
    }
  })
}
```
The file uploads properly but when downloading the file (using nats cli) it is corrupt and wont extract. It shouldn't matter but the example uses a gzipped file.

Any pointers for how the file should be passed in? The example is just encoding/decoding a string but I believe files are read in as a buffer type.

Thanks.

**Comment by aricart** [comment]
My guess is that because it is a Buffer, there may be some unexpected data in there...
Perhaps try obtaining the ArrayBuffer from Node's Buffer, and then creating an Uint8Array from it.

**Comment by aricart** [comment]
I went to look at the implementation, and it is possible for an entry to not have a hash, which would trigger it as being corrupt. Posting a fix right now.

**Comment by aricart** [comment]
This may not be your issue exactly, but could be, I will release @next versions of nats.ws so you can test.

**Comment by aricart** [comment]
@jmordica `npm install nats.ws@next` to get `1.10.0-1`

**Comment by jmordica** [comment]
Sweet! Installing the new version worked! For anyone else dealing with this here's how I am now successfully uploading a file to object store:
```js
await os.put({name: 'someFile.gz'}, this.readableStreamFrom(fs.readFileSync('path/to/someFile.gz')));
```
