### ISSUE TITLE
NatsError: wrong last sequence x

### ISSUE THREAD

**Issue by jsbrain** [nats-io/nats.deno#385]
I experimented with kv today and implemented the example found in the [README](https://github.com/nats-io/nats.deno/blob/main/jetstream.md#kv).

Somehow, I sometimes get this error. It's has definitely to do with the kv store, as I never experienced it before and the error vanishes when I delete the bucket and restart the app. Just restarting the nats server and restarting the app does not resolve the error and it persists after restart.

```text
[Nest] 97974  - 10/15/2022, 6:24:23 PM   ERROR [NatsError: wrong last sequence: 65
    at checkJsErrorCode (/Users/me/project/node_modules/nats/nats-base-client/jsutil.ts:177:14)
    at JetStreamClientImpl.parseJsResponse (/Users/me/project/node_modules/nats/nats-base-client/jsbaseclient_api.ts:106:35)
    at JetStreamClientImpl.<anonymous> (/Users/me/project/node_modules/nats/nats-base-client/jsclient.ts:189:21)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/project/node_modules/nats/lib/nats-base-client/jsclient.js:19:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)] wrong last sequence: 65
```

Any hints to what this error might point to? I'm not doing something crazy, just saving some keys into and JsonCodec encoded json into the kv.

This happened a few times now while developing but I didn't manage to reproduce it consistently by any means.

**Comment by jsbrain** [comment]
This is the actual code, in case it helps:

```ts
async getAllKvEntries() {
  const kv = await this.getKvInstance();
  const kvMap: Record<string, any> = {};

  const keys: string[] = [];
  const keysIterator = await kv.keys();
  await (async () => {
    for await (const key of keysIterator) {
      keys.push(key);
    }
  })();

  await (async () => {
    for (const key of keys) {
      const _entry = await kv.get(key);
      const value = this.decode(_entry?.value);
      const entry = { ..._entry, value };
      kvMap[key] = entry;
    }
  })();

  return kvMap;
}
```

**Comment by aricart** [comment]
That error is related to populating the keystone - are you calling elsewhere:
`kv.create()` on a key that exists, or are you updating a value `kv.update(key, value, version)` where version is some number?

**Comment by jsbrain** [comment]
Yes you're right. I did miss a line of code where I was doing exactly that.

So now I have this:

```ts
const entry = await kv.get(jobData.id);
if (entry) {
  await kv.update(jobData.id, sc.encode('done'), entry.revision);
}
```

which prevents the error and it works as intended so far.

Is this the correct way to handle it though or is there maybe a shorter/cleaner version?

**Comment by aricart** [comment]
if you want to make sure the keys are updated transactionally the above way is the correct one. Otherwise, you can just use `put()`.

**Comment by jsbrain** [comment]
Awesome. Thank you so much for the advice! 🥳
