### ISSUE TITLE
Allowing functions in the authenticator

### ISSUE THREAD

**Issue by Jontem** [nats-io/nats.deno#411]
As we discussed on slack @aricart (I hope i understood you correctly)

It should be possible to supply callback functions for supplying new credentials after connecting.

**Comment by aricart** [comment]
Yes this was possible before on some of them, but the values in some cases were obtained when the authenticator created, rather than deferred to when needed. This PR fixes that:

https://github.com/nats-io/nats.deno/pull/412/files

**Comment by aricart** [comment]
this is now merged.
