### ISSUE TITLE
Request for enhancement: provide a ConsumerConfigBuilder

### ISSUE THREAD

**Issue by pawoolley** [nats-io/nats.deno#425]
Something that has just had me questioning my sanity for the past few hours is the inconsistency between specifying `ack_wait` in either milliseconds or nanoseconds.

When working with `ConsumerOptsBuilder`, the `ackWait` value is millis, but if working with `ConsumerConfig` directly, which doesn't have a builder, it is nanos.  I didn't notice this straight away.

As a result, when setting up a consumer like this:
```javascript
await jetStreamManager.consumers.add(stream, {
    ack_policy: AckPolicy.Explicit,
    ack_wait: 3000, // this is nanos, not millis
})
```
...I was getting behaviour I didn't understand.  It wasn't until more closely reading the field comments that I realised that `ack_wait` should be expressed in **nanos**, not **millis**.

I think it would be a good enhancement to provide a `ConsumerConfigBuilder` that accepted `ackWait` in millis, just like `ConsumerOptsBuilder` does, so that the units across the two things are consistent and will (hopefully) avoid confusion with people like me in the future.

**Comment by aricart** [comment]
It doesn't help that the JS doc removes the type and replaces it with `number` even though it is typed as `Nanos`.

**Comment by aricart** [comment]
The new JetStream API removes the need for having the consumer builder (and deprecates all the subscribe calls), since the consumer is created with the JSM apis.
