### ISSUE TITLE
TypeScript typings/interface doesn't include JetStreamManager.direct

### ISSUE THREAD

**Issue by tothandras** [nats-io/nats.deno#497]
The [`.direct`](https://github.com/nats-io/nats.deno/blob/main/nats-base-client/jsm.ts#L40) API on `JetStreamManager` is missing from the [interface](https://github.com/nats-io/nats.deno/blob/main/nats-base-client/types.ts#L766)

**Comment by aricart** [comment]
Not yet making it available - directly... Let me think about it.

**Comment by aricart** [comment]
This API will not be exposed directly by the client as it is low-level - we are still implementing some of the features, at that point we will provide an API through the Stream object.
