### ISSUE TITLE
Consumer filterSubject appears to have no affect

### ISSUE THREAD

**Issue by jeffmccune** [nats-io/nats.deno#553]
I'm struggling to create an ordered consumer that filters to one subject of the stream.  Here's my code:

```javascript
    this.oc = await this.js.consumers.get(this.stream, {
      filterSubject: this.sub_subject,
    });

    console.log(this.oc);

    // Replay dom elements stored in JetStream
    const sc = StringCodec();

    await this.oc.consume({
      callback: (m) => {
        console.log(m.seq);
        // https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent
        const ev = new MessageEvent("message", {
          data: sc.decode(m.data),
          origin: m.subject,
          lastEventId: m.seq,
        });
        this._dispatchEvent("message", ev);
        m.ack();
      },
    });
```

Context:

I have a stream with max stream messages set to one.  There are two messages, one in each of two different subjects: `releases.one.elements` and `releases.two.elements`.

Expected behavior:

I expect to get one message from the subject `releases.one.elements` since the filter subject in the OrderedPullConsumerImpl is:

```
consumerOpts: 
  filterSubject: "releases.one.elements"
```

Actual behavior:

Both messages from both subjects are always sent.

Note, I tried `filterSubjects` as noted [here](https://github.com/nats-io/nats.deno/blob/main/jetstream.md#jetstream-ordered-consumers) but it doesn't work with nats-server 2.9.

Any tips on setting up a filter subject would be greatly appreciated.  Thanks!

**Comment by aricart** [comment]
@jeffmccune the `filterSubject` option is not valid, it should be `filterSubjects`, so it is defaulting to `>` as a filter.

Note that while the API states that it can take an array of subjects this feature will reject unless the server is 2.10.x (which is not yet released)

**Comment by aricart** [comment]
Also opened a PR to update the JS doc for that option (this lives in https://nats-io.github.io/nats.deno/)

**Comment by jeffmccune** [comment]
Thanks Alberto.  Is there no way to filter to one subject with the JavaScript libraries and 2.9 and the recommendation is to wait for the 2.10 release?  No problem if so, just need to know to plan accordingly.

**Comment by jeffmccune** [comment]
I got it working with:

```javascript
    const oc = await js.consumers.get("MY_STREAM", {
      filterSubjects: "my_subject",
    });
```
Thank you!
