### ISSUE TITLE
KvWatchInclude mistakenly exported as type

### ISSUE THREAD

**Issue by RaviVadera** [nats-io/nats.deno#657]
### Observed behavior

Compile time warning when using watch with option include: KvWatchInclude.UpdatesOnly.
'KvWatchInclude' cannot be used as a value because it was exported using 'export type'.ts(1362)
mod.d.ts(3, 796): 'KvWatchInclude' was exported here.

### Expected behavior

Should be possible to watch for KV with include: KvWatchInclude.UpdatesOnly option without compile time warning.

### Server and client version

Server Version: N/A
Client Version: ^2.19.0

### Steps to reproduce

Try to use KV watch with option include: KvWatchInclude.UpdatesOnly

**Comment by aricart** [comment]
you need to `import type {KvWatchInclude} from ...`

**Comment by RaviVadera** [comment]
Tried that already, getting similar result. I think enum needs to be exported without ```type``` keyword?
```'
KvWatchInclude' cannot be used as a value because it was imported using 'import type'.ts(1361)
nats.ts(6, 14): 'KvWatchInclude' was imported here.
```
