### ISSUE TITLE
Why crypto?.subtle?.digest may be not a function?

### ISSUE THREAD

**Issue by sheldygg** [nats-io/nats.deno#692]
### Observed behavior

I cant create ObjectStorage instance because I receive [this](https://github.com/nats-io/nats.deno/blob/66a47b9f49645685aaeca0980de779ac83946e7e/jetstream/jsclient.ts#L134) error
Do you know why is may be null?
Could you please help me fix that error?
I have installed latest versions of node and npm.

### Expected behavior

I want create ObjectStorage instance

### Server and client version

-

**Comment by aricart** [comment]
@sheldygg What runtime are you using? - if you don't have crypto.subtle you are going to have to shim it - that is standard dependency on ES compliant environments such as browsers and deno. For node it is automatically shimmed. As the error says:

` objectstore: unable to calculate hashes - crypto.subtle.digest with sha256 support is required` - we need to be able to hash the ObjectStore entries and the algorithm is sha256 - if you can shim it with an ES compatible version then you can use ObjectStore.

**Comment by aricart** [comment]
You can try printing what your runtime offers. - But `digest` should be a function.

**Comment by sheldygg** [comment]
> @sheldygg What runtime are you using? - if you don't have crypto.subtle you are going to have to shim it - that is standard dependency on ES compliant environments such as browsers and deno. For node it is automatically shimmed. As the error says:
> 
> ` objectstore: unable to calculate hashes - crypto.subtle.digest with sha256 support is required` - we need to be able to hash the ObjectStore entries and the algorithm is sha256 - if you can shim it with an ES compatible version then you can use ObjectStore.

I run on Ubuntu 22.04, on Windows 10 it works good without any manipulation. I use your library in next.js application.
![image](https://github.com/nats-io/nats.deno/assets/85823514/b8ba1f26-f2c6-4c54-b466-106668334a19)
I try to search in internet information about this, but doesn't see problem like mine. Do you know how i can install it or something?

**Comment by aricart** [comment]
you need to google for crypto.subtle shims and install one (maybe this - not sure https://www.npmjs.com/package/webcrypto-shim)

**Comment by sheldygg** [comment]
Okay, thank you.
