### ISSUE TITLE
Remove TLS check in checkOptions to allow "TLS auto"

### ISSUE THREAD

**Issue by mxmauro** [nats-io/nats.deno#714]
### Observed behavior

It is impossible to connect to a server that can have TLS enable or not.

If `tls` object in `options` is not set, then TLS is not supported.
If `tls.handshakeFirst = true`, then the server must have TLS enabled.

I assumed and [verified in code](https://github.com/nats-io/nats.deno/blob/main/src/deno_transport.ts#L61) that setting `tls.handshakeFirst = false` it will try to do a non-tls dial and then, if the server supports TLS, execute the handshake.

But the call to `checkOptions` fails if the server does not has TLS enabled and the options contains a `tls` object: https://github.com/nats-io/nats.deno/blob/main/nats-base-client/options.ts#L163

### Expected behavior

I expect the `checkOptions` to succeed and let the connection routine to continue.

I think the code should be something like this:

```
if (tlsRequired && (!options.tls?.handshakeFirst === true)) {
    throw new NatsError("tls", ErrorCode.ServerOptionNotAvailable);
}
```

### Server and client version

Client: v2.26
Server: v2.10.16

### Steps to reproduce

Just set `tls = {}` in connect's options and try to connect to a non-TLS server.

**Comment by aricart** [comment]
Very close, but not quite:

if tls options are provided, TLS is required (this includes handshakeFirst since it is a tls option)
If tls options are not specified, the client can connect to both TLS and non-TLS servers.
If set to null, it will not connect to a TLS enabled server

**Comment by mxmauro** [comment]
Ok but in this case, non-tls connection will be selected over the tls version. Is this intended?

**Comment by aricart** [comment]
it favors tls. The only time that non-tls is favored is if you specify `null` for the option
