### ISSUE TITLE
Publish with No-Responder

### ISSUE THREAD

**Issue by Zetanova** [nats-io/nats.deno#730]
### Proposed change

there is currently no positionality to publish a request on a custom reply subject and provide the same behavior like over `request` method with a fast failure with `No responders are available`.

a methoth like `nc.publishMessageAck(msg:Msg): Promise<Pick<MsgHdrs, 'hasError','status','code','description'>>`  is missing

### Use case

I need/want to use a custom replay subscription and utilize the nats `no-responders` feature.

**Comment by Jarema** [comment]
NATS request is just a `publish` with provided `reply` subject.

If you want to manually use request-reply pattern with your own subjects, you can simply:

```
  // Subscribe to "responses" subject
  const sub = nc.subscribe("responses");

 // Process messages from the "responses" subject
   ...

  // Publish a message to "requests" subject with a reply to "responses"
  nc.publish("requests", "Hello, World!", {
    reply: "responses",
  });
```

**Comment by Zetanova** [comment]
Thanks for testing, tried again with nats-cli 
```
$ nats sub "test.reply.>"
$ nats pub "test.service" --reply "test.reply.A" ""
```

It simply does not work for me, 
maybe because I am still on an older nats server v2.9.

**Comment by Zetanova** [comment]
maybe the client is ignoring the error message on a custom subscription?

**Comment by Zetanova** [comment]
Great, one mystery solved.

Is this the same reason why no-responders feature does not work with account import/export service? 
see [issue](https://github.com/nats-io/nats-server/discussions/4761)

The nats behavior seams a bit off, 
in osi model the last router/server should respond with the routing/forward error
